name: Test Workflow

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: 23f2003549@ds.study.iitm.ac.in
        run: echo "Hello, world!"
